CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE parcels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    county_id TEXT NOT NULL,
    county_code TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_parcel_id TEXT NOT NULL,
    parcel_number TEXT,
    account_number TEXT,
    parcel_year SMALLINT,

    current_name_1 TEXT,
    current_name_2 TEXT,
    tax_name_1 TEXT,
    tax_name_2 TEXT,
    tax_owner_id_1 TEXT,
    tax_owner_id_2 TEXT,

    mailing_line_1 TEXT,
    mailing_line_2 TEXT,
    mailing_city TEXT,
    mailing_state TEXT,
    mailing_postal_code TEXT,

    situs_line_1 TEXT,
    situs_line_2 TEXT,
    situs_city TEXT,
    situs_state TEXT,
    situs_postal_code TEXT,

    legal_description TEXT,
    plat_book TEXT,
    plat_page TEXT,
    deed_book TEXT,
    deed_page TEXT,

    land_code TEXT,
    land_type TEXT,
    property_use TEXT,
    subdivision TEXT,
    mapped_acres NUMERIC(14, 6),
    gross_acres NUMERIC(14, 6),
    valued_acres NUMERIC(14, 6),
    valued_sqft NUMERIC(16, 2),

    year_built SMALLINT,
    sqft NUMERIC(14, 2),
    basement TEXT,
    quality_code TEXT,
    structure TEXT,
    structure_style TEXT,

    valuation_land NUMERIC(14, 2),
    valuation_improvement NUMERIC(14, 2),
    valuation_total NUMERIC(14, 2),
    valuation_assessed NUMERIC(14, 2),

    shape GEOMETRY(Geometry, 3857),
    srid INTEGER NOT NULL DEFAULT 3857,
    source_srid INTEGER,
    source_area NUMERIC(20, 6),
    source_length NUMERIC(20, 6),

    source_extras JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT parcels_source_identity_unique UNIQUE (county_id, source_name, source_parcel_id),
    CONSTRAINT parcels_parcel_year_check CHECK (parcel_year IS NULL OR parcel_year BETWEEN 1900 AND 2200),
    CONSTRAINT parcels_year_built_check CHECK (year_built IS NULL OR year_built BETWEEN 1600 AND 2200),
    CONSTRAINT parcels_nonnegative_area_check CHECK (
        (mapped_acres IS NULL OR mapped_acres >= 0)
        AND (gross_acres IS NULL OR gross_acres >= 0)
        AND (valued_acres IS NULL OR valued_acres >= 0)
        AND (valued_sqft IS NULL OR valued_sqft >= 0)
        AND (sqft IS NULL OR sqft >= 0)
        AND (source_area IS NULL OR source_area >= 0)
        AND (source_length IS NULL OR source_length >= 0)
    ),
    CONSTRAINT parcels_nonnegative_valuation_check CHECK (
        (valuation_land IS NULL OR valuation_land >= 0)
        AND (valuation_improvement IS NULL OR valuation_improvement >= 0)
        AND (valuation_total IS NULL OR valuation_total >= 0)
        AND (valuation_assessed IS NULL OR valuation_assessed >= 0)
    ),
    CONSTRAINT parcels_srid_matches_shape CHECK (shape IS NULL OR ST_SRID(shape) = srid)
);

CREATE TABLE parcel_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id UUID NOT NULL REFERENCES parcels(id) ON DELETE CASCADE,
    sequence SMALLINT NOT NULL,
    sale_date DATE,
    og_sale_date BIGINT,
    amount NUMERIC(14, 2),
    deed_book TEXT,
    deed_page TEXT,
    deed_type TEXT,
    deed_quality TEXT,
    grantor TEXT,
    grantor_2 TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT parcel_sales_parcel_sequence_unique UNIQUE (parcel_id, sequence),
    CONSTRAINT parcel_sales_sequence_check CHECK (sequence > 0),
    CONSTRAINT parcel_sales_amount_nonnegative_check CHECK (amount IS NULL OR amount >= 0)
);

COMMENT ON COLUMN parcel_sales.sale_date IS 'Normalized sale calendar date from ArcGIS epoch milliseconds; time-of-day is intentionally not retained.';
COMMENT ON COLUMN parcel_sales.og_sale_date IS 'Original ArcGIS sale date value in Unix epoch milliseconds, retained for traceability.';

CREATE INDEX parcels_county_id_idx ON parcels (county_id);
CREATE INDEX parcels_county_code_idx ON parcels (county_code);
CREATE INDEX parcels_source_parcel_id_idx ON parcels (source_parcel_id);
CREATE INDEX parcels_parcel_number_idx ON parcels (parcel_number);
CREATE INDEX parcels_account_number_idx ON parcels (account_number);
CREATE INDEX parcels_source_extras_gin_idx ON parcels USING GIN (source_extras);
CREATE INDEX parcels_shape_gist_idx ON parcels USING GIST (shape);

CREATE INDEX parcel_sales_parcel_id_idx ON parcel_sales (parcel_id);
CREATE INDEX parcel_sales_sale_date_idx ON parcel_sales (sale_date);
